import type { VideoItem } from "@/components/video-card"

export type Artist = {
  id: string
  name: string
  image: string
  listeners: string
  bio: string
  genres: string[]
  tracks: VideoItem[]
}

export const artists: Artist[] = [
  {
    id: "1",
    name: "Marco Rivera",
    image: "/artists/artist-1.jpg",
    listeners: "24,502,318",
    bio: "Marco Rivera is a multi-platinum artist known for blending soulful vocals with modern production. His signature sound mixes R&B grooves with electronic textures.",
    genres: ["R&B", "Soul", "Electronic"],
    tracks: [
      {
        id: "marco-1",
        title: "Midnight Groove",
        artist: "Marco Rivera",
        album: "Night Sessions",
        thumbnailUrl: "/abstract-album-art.png",
        duration_ms: 214000,
      },
      {
        id: "marco-2",
        title: "City Lights",
        artist: "Marco Rivera",
        album: "Night Sessions",
        thumbnailUrl: "/abstract-album-art.png",
        duration_ms: 198000,
      },
      {
        id: "marco-3",
        title: "Velvet Sky",
        artist: "Marco Rivera",
        album: "Night Sessions",
        thumbnailUrl: "/abstract-album-art.png",
        duration_ms: 243000,
      },
      {
        id: "marco-4",
        title: "After Hours",
        artist: "Marco Rivera",
        album: "Reflections",
        thumbnailUrl: "/abstract-blend.png",
        duration_ms: 187000,
      },
      {
        id: "marco-5",
        title: "Silhouette",
        artist: "Marco Rivera",
        album: "Reflections",
        thumbnailUrl: "/abstract-blend.png",
        duration_ms: 221000,
      },
      {
        id: "marco-6",
        title: "Neon Dreams",
        artist: "Marco Rivera",
        album: "Reflections",
        thumbnailUrl: "/abstract-blend.png",
        duration_ms: 205000,
      },
      {
        id: "marco-7",
        title: "Whisper",
        artist: "Marco Rivera",
        album: "Echoes",
        thumbnailUrl: "/calm-ocean-sunset.png",
        duration_ms: 194000,
      },
      {
        id: "marco-8",
        title: "Fade Away",
        artist: "Marco Rivera",
        album: "Echoes",
        thumbnailUrl: "/calm-ocean-sunset.png",
        duration_ms: 232000,
      },
    ],
  },
  {
    id: "2",
    name: "Luna Vega",
    image: "/artists/artist-2.jpg",
    listeners: "31,205,412",
    bio: "Luna Vega burst onto the pop scene with her debut single and has since become one of the most streamed female artists. Her music combines catchy melodies with empowering lyrics.",
    genres: ["Pop", "Dance Pop", "Electropop"],
    tracks: [
      {
        id: "luna-1",
        title: "Electric Dreams",
        artist: "Luna Vega",
        album: "Neon Skies",
        thumbnailUrl: "/futuristic-sound-waves.png",
        duration_ms: 198000,
      },
      {
        id: "luna-2",
        title: "Starlight",
        artist: "Luna Vega",
        album: "Neon Skies",
        thumbnailUrl: "/futuristic-sound-waves.png",
        duration_ms: 213000,
      },
      {
        id: "luna-3",
        title: "Supernova",
        artist: "Luna Vega",
        album: "Neon Skies",
        thumbnailUrl: "/futuristic-sound-waves.png",
        duration_ms: 187000,
      },
      {
        id: "luna-4",
        title: "Heartbeat",
        artist: "Luna Vega",
        album: "Pulse",
        thumbnailUrl: "/generic-pop-album-cover.png",
        duration_ms: 224000,
      },
      {
        id: "luna-5",
        title: "Dancing in Fire",
        artist: "Luna Vega",
        album: "Pulse",
        thumbnailUrl: "/generic-pop-album-cover.png",
        duration_ms: 201000,
      },
      {
        id: "luna-6",
        title: "Gravity",
        artist: "Luna Vega",
        album: "Pulse",
        thumbnailUrl: "/generic-pop-album-cover.png",
        duration_ms: 195000,
      },
      {
        id: "luna-7",
        title: "Crystal Clear",
        artist: "Luna Vega",
        album: "Aurora",
        thumbnailUrl: "/abstract-colorful-gradient.png",
        duration_ms: 218000,
      },
    ],
  },
  {
    id: "3",
    name: "King Drako",
    image: "/artists/artist-3.jpg",
    listeners: "45,831,074",
    bio: "King Drako is a chart-topping hip-hop artist whose hard-hitting bars and cinematic beats have earned him a loyal global fanbase. Known for his storytelling and bold production.",
    genres: ["Hip-Hop", "Trap", "Rap"],
    tracks: [
      {
        id: "drako-1",
        title: "On Top",
        artist: "King Drako",
        album: "Crown",
        thumbnailUrl: "/generic-synthwave-album-cover.png",
        duration_ms: 241000,
      },
      {
        id: "drako-2",
        title: "No Mercy",
        artist: "King Drako",
        album: "Crown",
        thumbnailUrl: "/generic-synthwave-album-cover.png",
        duration_ms: 203000,
      },
      {
        id: "drako-3",
        title: "Rise Up",
        artist: "King Drako",
        album: "Crown",
        thumbnailUrl: "/generic-synthwave-album-cover.png",
        duration_ms: 218000,
      },
      {
        id: "drako-4",
        title: "Street Anthem",
        artist: "King Drako",
        album: "Legacy",
        thumbnailUrl: "/music-notes-dark.png",
        duration_ms: 195000,
      },
      {
        id: "drako-5",
        title: "Diamonds",
        artist: "King Drako",
        album: "Legacy",
        thumbnailUrl: "/music-notes-dark.png",
        duration_ms: 227000,
      },
      {
        id: "drako-6",
        title: "Kingdom Come",
        artist: "King Drako",
        album: "Legacy",
        thumbnailUrl: "/music-notes-dark.png",
        duration_ms: 252000,
      },
      {
        id: "drako-7",
        title: "Throne",
        artist: "King Drako",
        album: "Empire",
        thumbnailUrl: "/abstract-album-art.png",
        duration_ms: 199000,
      },
      {
        id: "drako-8",
        title: "Gold Chains",
        artist: "King Drako",
        album: "Empire",
        thumbnailUrl: "/abstract-album-art.png",
        duration_ms: 211000,
      },
      {
        id: "drako-9",
        title: "Unstoppable",
        artist: "King Drako",
        album: "Empire",
        thumbnailUrl: "/abstract-album-art.png",
        duration_ms: 238000,
      },
    ],
  },
  {
    id: "4",
    name: "Aria Soul",
    image: "/artists/artist-4.jpg",
    listeners: "18,923,556",
    bio: "Aria Soul brings warmth and vulnerability to modern R&B. Her soothing voice and heartfelt songwriting have made her a favorite among fans seeking authentic emotional connection.",
    genres: ["R&B", "Neo-Soul", "Jazz"],
    tracks: [
      {
        id: "aria-1",
        title: "Golden Hour",
        artist: "Aria Soul",
        album: "Sunlight",
        thumbnailUrl: "/calm-ocean-sunset.png",
        duration_ms: 187000,
      },
      {
        id: "aria-2",
        title: "Warm Embrace",
        artist: "Aria Soul",
        album: "Sunlight",
        thumbnailUrl: "/calm-ocean-sunset.png",
        duration_ms: 215000,
      },
      {
        id: "aria-3",
        title: "Honey",
        artist: "Aria Soul",
        album: "Sunlight",
        thumbnailUrl: "/calm-ocean-sunset.png",
        duration_ms: 198000,
      },
      {
        id: "aria-4",
        title: "Tender Love",
        artist: "Aria Soul",
        album: "Bloom",
        thumbnailUrl: "/peaches-album-cover.png",
        duration_ms: 224000,
      },
      {
        id: "aria-5",
        title: "Moonlit",
        artist: "Aria Soul",
        album: "Bloom",
        thumbnailUrl: "/peaches-album-cover.png",
        duration_ms: 191000,
      },
      {
        id: "aria-6",
        title: "Roses",
        artist: "Aria Soul",
        album: "Bloom",
        thumbnailUrl: "/peaches-album-cover.png",
        duration_ms: 207000,
      },
    ],
  },
  {
    id: "5",
    name: "Axel Stone",
    image: "/artists/artist-5.jpg",
    listeners: "22,109,882",
    bio: "Axel Stone is a rock powerhouse blending classic guitar riffs with modern alternative sounds. His high-energy performances and anthemic tracks have made him a live favorite.",
    genres: ["Rock", "Alternative", "Indie Rock"],
    tracks: [
      {
        id: "axel-1",
        title: "Break Free",
        artist: "Axel Stone",
        album: "Revolt",
        thumbnailUrl: "/abstract-blend.png",
        duration_ms: 225000,
      },
      {
        id: "axel-2",
        title: "Thunder Road",
        artist: "Axel Stone",
        album: "Revolt",
        thumbnailUrl: "/abstract-blend.png",
        duration_ms: 248000,
      },
      {
        id: "axel-3",
        title: "Wildfire",
        artist: "Axel Stone",
        album: "Revolt",
        thumbnailUrl: "/abstract-blend.png",
        duration_ms: 212000,
      },
      {
        id: "axel-4",
        title: "Edge of Glory",
        artist: "Axel Stone",
        album: "Echoes of Steel",
        thumbnailUrl: "/heat-waves-album-cover.png",
        duration_ms: 237000,
      },
      {
        id: "axel-5",
        title: "Burning Bright",
        artist: "Axel Stone",
        album: "Echoes of Steel",
        thumbnailUrl: "/heat-waves-album-cover.png",
        duration_ms: 199000,
      },
      {
        id: "axel-6",
        title: "Iron Will",
        artist: "Axel Stone",
        album: "Echoes of Steel",
        thumbnailUrl: "/heat-waves-album-cover.png",
        duration_ms: 264000,
      },
      {
        id: "axel-7",
        title: "Rebel Heart",
        artist: "Axel Stone",
        album: "Unbroken",
        thumbnailUrl: "/minimalist-geometric-patterns.png",
        duration_ms: 221000,
      },
    ],
  },
  {
    id: "6",
    name: "Ivy Monroe",
    image: "/artists/artist-6.jpg",
    listeners: "15,712,390",
    bio: "Ivy Monroe is a singer-songwriter whose folk-inspired melodies and poetic lyrics paint vivid emotional landscapes. Her acoustic performances are intimate and unforgettable.",
    genres: ["Indie", "Folk", "Singer-Songwriter"],
    tracks: [
      {
        id: "ivy-1",
        title: "Paper Hearts",
        artist: "Ivy Monroe",
        album: "Wildflower",
        thumbnailUrl: "/calm-ocean-sunset.png",
        duration_ms: 204000,
      },
      {
        id: "ivy-2",
        title: "Morning Dew",
        artist: "Ivy Monroe",
        album: "Wildflower",
        thumbnailUrl: "/calm-ocean-sunset.png",
        duration_ms: 192000,
      },
      {
        id: "ivy-3",
        title: "Autumn Leaves",
        artist: "Ivy Monroe",
        album: "Wildflower",
        thumbnailUrl: "/calm-ocean-sunset.png",
        duration_ms: 218000,
      },
      {
        id: "ivy-4",
        title: "River Song",
        artist: "Ivy Monroe",
        album: "Whispers",
        thumbnailUrl: "/minimalist-geometric-patterns.png",
        duration_ms: 231000,
      },
      {
        id: "ivy-5",
        title: "Lantern Light",
        artist: "Ivy Monroe",
        album: "Whispers",
        thumbnailUrl: "/minimalist-geometric-patterns.png",
        duration_ms: 197000,
      },
    ],
  },
  {
    id: "7",
    name: "El Fuego",
    image: "/artists/artist-7.jpg",
    listeners: "38,401,229",
    bio: "El Fuego is a Latin music sensation whose reggaeton and Latin pop tracks dominate charts worldwide. His infectious rhythms and charismatic delivery keep fans coming back for more.",
    genres: ["Reggaeton", "Latin Pop", "Urbano"],
    tracks: [
      {
        id: "fuego-1",
        title: "Fuego Lento",
        artist: "El Fuego",
        album: "Caliente",
        thumbnailUrl: "/abstract-colorful-gradient.png",
        duration_ms: 196000,
      },
      {
        id: "fuego-2",
        title: "Bailamos",
        artist: "El Fuego",
        album: "Caliente",
        thumbnailUrl: "/abstract-colorful-gradient.png",
        duration_ms: 211000,
      },
      {
        id: "fuego-3",
        title: "La Noche",
        artist: "El Fuego",
        album: "Caliente",
        thumbnailUrl: "/abstract-colorful-gradient.png",
        duration_ms: 184000,
      },
      {
        id: "fuego-4",
        title: "Ritmo",
        artist: "El Fuego",
        album: "Tropicana",
        thumbnailUrl: "/peaches-album-cover.png",
        duration_ms: 203000,
      },
      {
        id: "fuego-5",
        title: "Corazon",
        artist: "El Fuego",
        album: "Tropicana",
        thumbnailUrl: "/peaches-album-cover.png",
        duration_ms: 227000,
      },
      {
        id: "fuego-6",
        title: "Prendelo",
        artist: "El Fuego",
        album: "Tropicana",
        thumbnailUrl: "/peaches-album-cover.png",
        duration_ms: 189000,
      },
      {
        id: "fuego-7",
        title: "Calor",
        artist: "El Fuego",
        album: "Fuego Eterno",
        thumbnailUrl: "/stay-album-cover.png",
        duration_ms: 215000,
      },
      {
        id: "fuego-8",
        title: "Libertad",
        artist: "El Fuego",
        album: "Fuego Eterno",
        thumbnailUrl: "/stay-album-cover.png",
        duration_ms: 242000,
      },
    ],
  },
  {
    id: "8",
    name: "Nova Beats",
    image: "/artists/artist-8.jpg",
    listeners: "27,318,445",
    bio: "Nova Beats is an electronic music producer and DJ whose pulsing basslines and ethereal synths create immersive sonic experiences. A headliner at festivals around the globe.",
    genres: ["Electronic", "House", "Techno"],
    tracks: [
      {
        id: "nova-1",
        title: "Pulse",
        artist: "Nova Beats",
        album: "Frequency",
        thumbnailUrl: "/futuristic-sound-waves.png",
        duration_ms: 302000,
      },
      {
        id: "nova-2",
        title: "Hyperdrive",
        artist: "Nova Beats",
        album: "Frequency",
        thumbnailUrl: "/futuristic-sound-waves.png",
        duration_ms: 278000,
      },
      {
        id: "nova-3",
        title: "Nebula",
        artist: "Nova Beats",
        album: "Frequency",
        thumbnailUrl: "/futuristic-sound-waves.png",
        duration_ms: 324000,
      },
      {
        id: "nova-4",
        title: "Solar Flare",
        artist: "Nova Beats",
        album: "Cosmos",
        thumbnailUrl: "/generic-synthwave-album-cover.png",
        duration_ms: 291000,
      },
      {
        id: "nova-5",
        title: "Zero Gravity",
        artist: "Nova Beats",
        album: "Cosmos",
        thumbnailUrl: "/generic-synthwave-album-cover.png",
        duration_ms: 267000,
      },
      {
        id: "nova-6",
        title: "Deep Space",
        artist: "Nova Beats",
        album: "Cosmos",
        thumbnailUrl: "/generic-synthwave-album-cover.png",
        duration_ms: 345000,
      },
      {
        id: "nova-7",
        title: "Waveform",
        artist: "Nova Beats",
        album: "Signal",
        thumbnailUrl: "/abstract-blend.png",
        duration_ms: 256000,
      },
      {
        id: "nova-8",
        title: "Echo Chamber",
        artist: "Nova Beats",
        album: "Signal",
        thumbnailUrl: "/abstract-blend.png",
        duration_ms: 289000,
      },
    ],
  },
]

export function getArtistById(id: string): Artist | undefined {
  return artists.find((a) => a.id === id)
}
