import type { VideoItem } from "@/components/video-card"

export type Artist = {
  id: string
  name: string
  image: string
  listeners: string
  bio: string
  genres: string[]
  tracks: VideoItem[]
}

export const artists: Artist[] = [
  {
    id: "1",
    name: "Bad Bunny",
    image: "/artists/bad-bunny.jpg",
    listeners: "72,534,892",
    bio: "Bad Bunny es un cantante y rapero puertorriqueno que ha revolucionado la musica latina con su estilo unico de reggaeton y trap latino. Es el artista mas escuchado en el mundo.",
    genres: ["Reggaeton", "Latin Trap", "Urbano Latino"],
    tracks: [
      {
        id: "bb-1",
        title: "Titi Me Pregunto",
        artist: "Bad Bunny",
        album: "Un Verano Sin Ti",
        thumbnailUrl: "/abstract-colorful-gradient.png",
        duration_ms: 244000,
        preview_url: "https://cdns-preview-d.dzcdn.net/stream/c-d7d3c0e4a3a2b0e0d3d0c7a3b2a1c0d7-3.mp3",
      },
      {
        id: "bb-2",
        title: "Me Porto Bonito",
        artist: "Bad Bunny ft. Chencho Corleone",
        album: "Un Verano Sin Ti",
        thumbnailUrl: "/abstract-colorful-gradient.png",
        duration_ms: 178000,
        preview_url: "https://cdns-preview-d.dzcdn.net/stream/c-d7d3c0e4a3a2b0e0d3d0c7a3b2a1c0d7-3.mp3",
      },
      {
        id: "bb-3",
        title: "Efecto",
        artist: "Bad Bunny",
        album: "Un Verano Sin Ti",
        thumbnailUrl: "/abstract-colorful-gradient.png",
        duration_ms: 206000,
        preview_url: "https://cdns-preview-d.dzcdn.net/stream/c-d7d3c0e4a3a2b0e0d3d0c7a3b2a1c0d7-3.mp3",
      },
      {
        id: "bb-4",
        title: "Dakiti",
        artist: "Bad Bunny ft. Jhay Cortez",
        album: "El Ultimo Tour Del Mundo",
        thumbnailUrl: "/generic-synthwave-album-cover.png",
        duration_ms: 205000,
        preview_url: "https://cdns-preview-d.dzcdn.net/stream/c-d7d3c0e4a3a2b0e0d3d0c7a3b2a1c0d7-3.mp3",
      },
      {
        id: "bb-5",
        title: "Yonaguni",
        artist: "Bad Bunny",
        album: "Single",
        thumbnailUrl: "/futuristic-sound-waves.png",
        duration_ms: 206000,
        preview_url: "https://cdns-preview-d.dzcdn.net/stream/c-d7d3c0e4a3a2b0e0d3d0c7a3b2a1c0d7-3.mp3",
      },
      {
        id: "bb-6",
        title: "Callaita",
        artist: "Bad Bunny",
        album: "Single",
        thumbnailUrl: "/calm-ocean-sunset.png",
        duration_ms: 251000,
        preview_url: "https://cdns-preview-d.dzcdn.net/stream/c-d7d3c0e4a3a2b0e0d3d0c7a3b2a1c0d7-3.mp3",
      },
      {
        id: "bb-7",
        title: "Vete",
        artist: "Bad Bunny",
        album: "YHLQMDLG",
        thumbnailUrl: "/abstract-blend.png",
        duration_ms: 191000,
        preview_url: "https://cdns-preview-d.dzcdn.net/stream/c-d7d3c0e4a3a2b0e0d3d0c7a3b2a1c0d7-3.mp3",
      },
      {
        id: "bb-8",
        title: "La Noche de Anoche",
        artist: "Bad Bunny ft. Rosalia",
        album: "El Ultimo Tour Del Mundo",
        thumbnailUrl: "/generic-synthwave-album-cover.png",
        duration_ms: 191000,
        preview_url: "https://cdns-preview-d.dzcdn.net/stream/c-d7d3c0e4a3a2b0e0d3d0c7a3b2a1c0d7-3.mp3",
      },
    ],
  },
  {
    id: "2",
    name: "Anuel AA",
    image: "/artists/anuel-aa.jpg",
    listeners: "45,231,567",
    bio: "Anuel AA es un rapero y cantante puertorriqueno, pionero del trap latino. Conocido por su estilo agresivo y letras callejeras, ha colaborado con los artistas mas grandes de la industria.",
    genres: ["Latin Trap", "Reggaeton", "Hip-Hop Latino"],
    tracks: [
      {
        id: "anuel-1",
        title: "China",
        artist: "Anuel AA, Daddy Yankee, Karol G",
        album: "Emmanuel",
        thumbnailUrl: "/abstract-colorful-gradient.png",
        duration_ms: 309000,
        preview_url: "https://cdns-preview-d.dzcdn.net/stream/c-d7d3c0e4a3a2b0e0d3d0c7a3b2a1c0d7-3.mp3",
      },
      {
        id: "anuel-2",
        title: "Secreto",
        artist: "Anuel AA ft. Karol G",
        album: "Real Hasta La Muerte",
        thumbnailUrl: "/peaches-album-cover.png",
        duration_ms: 224000,
        preview_url: "https://cdns-preview-d.dzcdn.net/stream/c-d7d3c0e4a3a2b0e0d3d0c7a3b2a1c0d7-3.mp3",
      },
      {
        id: "anuel-3",
        title: "Ella Quiere Beber",
        artist: "Anuel AA ft. Romeo Santos",
        album: "Real Hasta La Muerte",
        thumbnailUrl: "/peaches-album-cover.png",
        duration_ms: 275000,
        preview_url: "https://cdns-preview-d.dzcdn.net/stream/c-d7d3c0e4a3a2b0e0d3d0c7a3b2a1c0d7-3.mp3",
      },
      {
        id: "anuel-4",
        title: "Sola",
        artist: "Anuel AA",
        album: "Real Hasta La Muerte",
        thumbnailUrl: "/peaches-album-cover.png",
        duration_ms: 247000,
        preview_url: "https://cdns-preview-d.dzcdn.net/stream/c-d7d3c0e4a3a2b0e0d3d0c7a3b2a1c0d7-3.mp3",
      },
      {
        id: "anuel-5",
        title: "Brindemos",
        artist: "Anuel AA ft. Ozuna",
        album: "Emmanuel",
        thumbnailUrl: "/abstract-colorful-gradient.png",
        duration_ms: 212000,
        preview_url: "https://cdns-preview-d.dzcdn.net/stream/c-d7d3c0e4a3a2b0e0d3d0c7a3b2a1c0d7-3.mp3",
      },
      {
        id: "anuel-6",
        title: "Hasta Que Dios Diga",
        artist: "Anuel AA ft. Bad Bunny",
        album: "Emmanuel",
        thumbnailUrl: "/abstract-colorful-gradient.png",
        duration_ms: 232000,
        preview_url: "https://cdns-preview-d.dzcdn.net/stream/c-d7d3c0e4a3a2b0e0d3d0c7a3b2a1c0d7-3.mp3",
      },
    ],
  },
  {
    id: "3",
    name: "Daddy Yankee",
    image: "/artists/daddy-yankee.jpg",
    listeners: "52,109,234",
    bio: "Daddy Yankee es el Rey del Reggaeton y uno de los artistas latinos mas influyentes de todos los tiempos. Su cancion 'Gasolina' llevo el reggaeton al mundo entero.",
    genres: ["Reggaeton", "Latin Pop", "Urbano"],
    tracks: [
      {
        id: "dy-1",
        title: "Gasolina",
        artist: "Daddy Yankee",
        album: "Barrio Fino",
        thumbnailUrl: "/generic-synthwave-album-cover.png",
        duration_ms: 192000,
        preview_url: "https://cdns-preview-d.dzcdn.net/stream/c-d7d3c0e4a3a2b0e0d3d0c7a3b2a1c0d7-3.mp3",
      },
      {
        id: "dy-2",
        title: "Despacito",
        artist: "Luis Fonsi ft. Daddy Yankee",
        album: "Vida",
        thumbnailUrl: "/calm-ocean-sunset.png",
        duration_ms: 229000,
        preview_url: "https://cdns-preview-d.dzcdn.net/stream/c-d7d3c0e4a3a2b0e0d3d0c7a3b2a1c0d7-3.mp3",
      },
      {
        id: "dy-3",
        title: "Con Calma",
        artist: "Daddy Yankee ft. Snow",
        album: "Con Calma",
        thumbnailUrl: "/futuristic-sound-waves.png",
        duration_ms: 193000,
        preview_url: "https://cdns-preview-d.dzcdn.net/stream/c-d7d3c0e4a3a2b0e0d3d0c7a3b2a1c0d7-3.mp3",
      },
      {
        id: "dy-4",
        title: "Dura",
        artist: "Daddy Yankee",
        album: "Legendaddy",
        thumbnailUrl: "/abstract-blend.png",
        duration_ms: 211000,
        preview_url: "https://cdns-preview-d.dzcdn.net/stream/c-d7d3c0e4a3a2b0e0d3d0c7a3b2a1c0d7-3.mp3",
      },
      {
        id: "dy-5",
        title: "Shaky Shaky",
        artist: "Daddy Yankee",
        album: "King Daddy",
        thumbnailUrl: "/abstract-album-art.png",
        duration_ms: 199000,
        preview_url: "https://cdns-preview-d.dzcdn.net/stream/c-d7d3c0e4a3a2b0e0d3d0c7a3b2a1c0d7-3.mp3",
      },
      {
        id: "dy-6",
        title: "Rompe",
        artist: "Daddy Yankee",
        album: "Barrio Fino En Directo",
        thumbnailUrl: "/generic-synthwave-album-cover.png",
        duration_ms: 245000,
        preview_url: "https://cdns-preview-d.dzcdn.net/stream/c-d7d3c0e4a3a2b0e0d3d0c7a3b2a1c0d7-3.mp3",
      },
    ],
  },
  {
    id: "4",
    name: "Karol G",
    image: "/artists/karol-g.jpg",
    listeners: "58,923,456",
    bio: "Karol G es una cantante colombiana que ha conquistado el mundo con su reggaeton y musica urbana. Es conocida como 'La Bichota' y es una de las artistas latinas mas exitosas.",
    genres: ["Reggaeton", "Latin Pop", "Urbano"],
    tracks: [
      {
        id: "kg-1",
        title: "Tusa",
        artist: "Karol G ft. Nicki Minaj",
        album: "KG0516",
        thumbnailUrl: "/abstract-colorful-gradient.png",
        duration_ms: 200000,
        preview_url: "https://cdns-preview-d.dzcdn.net/stream/c-d7d3c0e4a3a2b0e0d3d0c7a3b2a1c0d7-3.mp3",
      },
      {
        id: "kg-2",
        title: "Provenza",
        artist: "Karol G",
        album: "Manana Sera Bonito",
        thumbnailUrl: "/peaches-album-cover.png",
        duration_ms: 212000,
        preview_url: "https://cdns-preview-d.dzcdn.net/stream/c-d7d3c0e4a3a2b0e0d3d0c7a3b2a1c0d7-3.mp3",
      },
      {
        id: "kg-3",
        title: "TQG",
        artist: "Karol G ft. Shakira",
        album: "Manana Sera Bonito",
        thumbnailUrl: "/peaches-album-cover.png",
        duration_ms: 198000,
        preview_url: "https://cdns-preview-d.dzcdn.net/stream/c-d7d3c0e4a3a2b0e0d3d0c7a3b2a1c0d7-3.mp3",
      },
      {
        id: "kg-4",
        title: "Bichota",
        artist: "Karol G",
        album: "KG0516",
        thumbnailUrl: "/abstract-colorful-gradient.png",
        duration_ms: 186000,
        preview_url: "https://cdns-preview-d.dzcdn.net/stream/c-d7d3c0e4a3a2b0e0d3d0c7a3b2a1c0d7-3.mp3",
      },
      {
        id: "kg-5",
        title: "Mamiii",
        artist: "Becky G ft. Karol G",
        album: "Mamiii",
        thumbnailUrl: "/futuristic-sound-waves.png",
        duration_ms: 209000,
        preview_url: "https://cdns-preview-d.dzcdn.net/stream/c-d7d3c0e4a3a2b0e0d3d0c7a3b2a1c0d7-3.mp3",
      },
      {
        id: "kg-6",
        title: "Mientras Me Curo del Cora",
        artist: "Karol G",
        album: "Manana Sera Bonito",
        thumbnailUrl: "/peaches-album-cover.png",
        duration_ms: 221000,
        preview_url: "https://cdns-preview-d.dzcdn.net/stream/c-d7d3c0e4a3a2b0e0d3d0c7a3b2a1c0d7-3.mp3",
      },
    ],
  },
  {
    id: "5",
    name: "J Balvin",
    image: "/artists/j-balvin.jpg",
    listeners: "48,109,882",
    bio: "J Balvin es un cantante colombiano conocido como el 'Principe del Reggaeton'. Ha llevado la musica urbana latina a nuevas alturas con colaboraciones internacionales y exitos globales.",
    genres: ["Reggaeton", "Latin Pop", "Urbano"],
    tracks: [
      {
        id: "jb-1",
        title: "Mi Gente",
        artist: "J Balvin ft. Willy William",
        album: "Vibras",
        thumbnailUrl: "/abstract-colorful-gradient.png",
        duration_ms: 189000,
        preview_url: "https://cdns-preview-d.dzcdn.net/stream/c-d7d3c0e4a3a2b0e0d3d0c7a3b2a1c0d7-3.mp3",
      },
      {
        id: "jb-2",
        title: "Ginza",
        artist: "J Balvin",
        album: "Energia",
        thumbnailUrl: "/generic-synthwave-album-cover.png",
        duration_ms: 228000,
        preview_url: "https://cdns-preview-d.dzcdn.net/stream/c-d7d3c0e4a3a2b0e0d3d0c7a3b2a1c0d7-3.mp3",
      },
      {
        id: "jb-3",
        title: "Ay Vamos",
        artist: "J Balvin",
        album: "Energia",
        thumbnailUrl: "/generic-synthwave-album-cover.png",
        duration_ms: 233000,
        preview_url: "https://cdns-preview-d.dzcdn.net/stream/c-d7d3c0e4a3a2b0e0d3d0c7a3b2a1c0d7-3.mp3",
      },
      {
        id: "jb-4",
        title: "Safari",
        artist: "J Balvin ft. Pharrell",
        album: "Energia",
        thumbnailUrl: "/generic-synthwave-album-cover.png",
        duration_ms: 228000,
        preview_url: "https://cdns-preview-d.dzcdn.net/stream/c-d7d3c0e4a3a2b0e0d3d0c7a3b2a1c0d7-3.mp3",
      },
      {
        id: "jb-5",
        title: "Ambiente",
        artist: "J Balvin",
        album: "Vibras",
        thumbnailUrl: "/abstract-colorful-gradient.png",
        duration_ms: 196000,
        preview_url: "https://cdns-preview-d.dzcdn.net/stream/c-d7d3c0e4a3a2b0e0d3d0c7a3b2a1c0d7-3.mp3",
      },
      {
        id: "jb-6",
        title: "Bobo",
        artist: "J Balvin",
        album: "Energia",
        thumbnailUrl: "/generic-synthwave-album-cover.png",
        duration_ms: 204000,
        preview_url: "https://cdns-preview-d.dzcdn.net/stream/c-d7d3c0e4a3a2b0e0d3d0c7a3b2a1c0d7-3.mp3",
      },
    ],
  },
  {
    id: "6",
    name: "Ozuna",
    image: "/artists/ozuna.jpg",
    listeners: "42,712,390",
    bio: "Ozuna es un cantante puertorriqueno de reggaeton y trap latino. Conocido como 'El Negrito de Ojos Claros', ha roto records con sus videos musicales y colaboraciones.",
    genres: ["Reggaeton", "Latin Trap", "Latin Pop"],
    tracks: [
      {
        id: "oz-1",
        title: "Te Bote",
        artist: "Ozuna ft. Bad Bunny, Nicky Jam",
        album: "Aura",
        thumbnailUrl: "/abstract-blend.png",
        duration_ms: 428000,
        preview_url: "https://cdns-preview-d.dzcdn.net/stream/c-d7d3c0e4a3a2b0e0d3d0c7a3b2a1c0d7-3.mp3",
      },
      {
        id: "oz-2",
        title: "El Farsante",
        artist: "Ozuna",
        album: "Odisea",
        thumbnailUrl: "/calm-ocean-sunset.png",
        duration_ms: 294000,
        preview_url: "https://cdns-preview-d.dzcdn.net/stream/c-d7d3c0e4a3a2b0e0d3d0c7a3b2a1c0d7-3.mp3",
      },
      {
        id: "oz-3",
        title: "Se Preparo",
        artist: "Ozuna",
        album: "Odisea",
        thumbnailUrl: "/calm-ocean-sunset.png",
        duration_ms: 254000,
        preview_url: "https://cdns-preview-d.dzcdn.net/stream/c-d7d3c0e4a3a2b0e0d3d0c7a3b2a1c0d7-3.mp3",
      },
      {
        id: "oz-4",
        title: "Criminal",
        artist: "Ozuna ft. Natti Natasha",
        album: "Odisea",
        thumbnailUrl: "/calm-ocean-sunset.png",
        duration_ms: 204000,
        preview_url: "https://cdns-preview-d.dzcdn.net/stream/c-d7d3c0e4a3a2b0e0d3d0c7a3b2a1c0d7-3.mp3",
      },
      {
        id: "oz-5",
        title: "Dile Que Tu Me Quieres",
        artist: "Ozuna",
        album: "Odisea",
        thumbnailUrl: "/calm-ocean-sunset.png",
        duration_ms: 266000,
        preview_url: "https://cdns-preview-d.dzcdn.net/stream/c-d7d3c0e4a3a2b0e0d3d0c7a3b2a1c0d7-3.mp3",
      },
    ],
  },
  {
    id: "7",
    name: "Rauw Alejandro",
    image: "/artists/rauw-alejandro.jpg",
    listeners: "38,401,229",
    bio: "Rauw Alejandro es un cantante puertorriqueno de reggaeton y R&B latino. Conocido por su estilo fresco y bailes innovadores, es uno de los nuevos iconos de la musica urbana.",
    genres: ["Reggaeton", "R&B Latino", "Urbano"],
    tracks: [
      {
        id: "ra-1",
        title: "Todo de Ti",
        artist: "Rauw Alejandro",
        album: "Vice Versa",
        thumbnailUrl: "/futuristic-sound-waves.png",
        duration_ms: 197000,
        preview_url: "https://cdns-preview-d.dzcdn.net/stream/c-d7d3c0e4a3a2b0e0d3d0c7a3b2a1c0d7-3.mp3",
      },
      {
        id: "ra-2",
        title: "Fantasias",
        artist: "Rauw Alejandro ft. Farruko",
        album: "Afrodisiaco",
        thumbnailUrl: "/abstract-album-art.png",
        duration_ms: 211000,
        preview_url: "https://cdns-preview-d.dzcdn.net/stream/c-d7d3c0e4a3a2b0e0d3d0c7a3b2a1c0d7-3.mp3",
      },
      {
        id: "ra-3",
        title: "2/Catorce",
        artist: "Rauw Alejandro",
        album: "Afrodisiaco",
        thumbnailUrl: "/abstract-album-art.png",
        duration_ms: 184000,
        preview_url: "https://cdns-preview-d.dzcdn.net/stream/c-d7d3c0e4a3a2b0e0d3d0c7a3b2a1c0d7-3.mp3",
      },
      {
        id: "ra-4",
        title: "Coco",
        artist: "Rauw Alejandro",
        album: "Vice Versa",
        thumbnailUrl: "/futuristic-sound-waves.png",
        duration_ms: 203000,
        preview_url: "https://cdns-preview-d.dzcdn.net/stream/c-d7d3c0e4a3a2b0e0d3d0c7a3b2a1c0d7-3.mp3",
      },
      {
        id: "ra-5",
        title: "Museo",
        artist: "Rauw Alejandro",
        album: "Vice Versa",
        thumbnailUrl: "/futuristic-sound-waves.png",
        duration_ms: 227000,
        preview_url: "https://cdns-preview-d.dzcdn.net/stream/c-d7d3c0e4a3a2b0e0d3d0c7a3b2a1c0d7-3.mp3",
      },
      {
        id: "ra-6",
        title: "Desenfocao",
        artist: "Rauw Alejandro",
        album: "Vice Versa",
        thumbnailUrl: "/futuristic-sound-waves.png",
        duration_ms: 189000,
        preview_url: "https://cdns-preview-d.dzcdn.net/stream/c-d7d3c0e4a3a2b0e0d3d0c7a3b2a1c0d7-3.mp3",
      },
    ],
  },
  {
    id: "8",
    name: "Feid",
    image: "/artists/feid.jpg",
    listeners: "35,318,445",
    bio: "Feid es un cantante y compositor colombiano conocido por su estilo de reggaeton melodico. Ha colaborado con los mas grandes y es reconocido por hits como 'Porfa' y 'Normal'.",
    genres: ["Reggaeton", "Latin Pop", "Urbano"],
    tracks: [
      {
        id: "feid-1",
        title: "Normal",
        artist: "Feid",
        album: "Inter Shibuya - La Mafia",
        thumbnailUrl: "/abstract-blend.png",
        duration_ms: 302000,
        preview_url: "https://cdns-preview-d.dzcdn.net/stream/c-d7d3c0e4a3a2b0e0d3d0c7a3b2a1c0d7-3.mp3",
      },
      {
        id: "feid-2",
        title: "Porfa",
        artist: "Feid ft. J Balvin",
        album: "FERXXO VOL 1",
        thumbnailUrl: "/generic-synthwave-album-cover.png",
        duration_ms: 278000,
        preview_url: "https://cdns-preview-d.dzcdn.net/stream/c-d7d3c0e4a3a2b0e0d3d0c7a3b2a1c0d7-3.mp3",
      },
      {
        id: "feid-3",
        title: "Feliz Cumpleanos Ferxxo",
        artist: "Feid",
        album: "Feliz Cumpleanos Ferxxo",
        thumbnailUrl: "/peaches-album-cover.png",
        duration_ms: 324000,
        preview_url: "https://cdns-preview-d.dzcdn.net/stream/c-d7d3c0e4a3a2b0e0d3d0c7a3b2a1c0d7-3.mp3",
      },
      {
        id: "feid-4",
        title: "Fumeteo",
        artist: "Feid",
        album: "Inter Shibuya - La Mafia",
        thumbnailUrl: "/abstract-blend.png",
        duration_ms: 291000,
        preview_url: "https://cdns-preview-d.dzcdn.net/stream/c-d7d3c0e4a3a2b0e0d3d0c7a3b2a1c0d7-3.mp3",
      },
      {
        id: "feid-5",
        title: "Castigo",
        artist: "Feid",
        album: "Inter Shibuya - La Mafia",
        thumbnailUrl: "/abstract-blend.png",
        duration_ms: 267000,
        preview_url: "https://cdns-preview-d.dzcdn.net/stream/c-d7d3c0e4a3a2b0e0d3d0c7a3b2a1c0d7-3.mp3",
      },
      {
        id: "feid-6",
        title: "Brickell",
        artist: "Feid ft. Yandel",
        album: "MOR",
        thumbnailUrl: "/stay-album-cover.png",
        duration_ms: 345000,
        preview_url: "https://cdns-preview-d.dzcdn.net/stream/c-d7d3c0e4a3a2b0e0d3d0c7a3b2a1c0d7-3.mp3",
      },
    ],
  },
]

export function getArtistById(id: string): Artist | undefined {
  return artists.find((a) => a.id === id)
}
